# Generated by Django 5.2.4 on 2025-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_emailcenter_customuser_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
