# Generated by Django 5.2.4 on 2025-08-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcenter',
            name='can_add_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcenter',
            name='can_download_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcenter',
            name='can_share_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcenter',
            name='can_upload_feed',
            field=models.BooleanField(default=False),
        ),
    ]
