# Generated by Django 5.2.4 on 2025-08-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_emailcenter_can_add_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcenter',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcenter',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
