# Generated by Django 5.2.4 on 2025-08-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0007_emailcenter_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcenter',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
