# Generated by Django 5.2.4 on 2025-10-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcenter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
