# Generated by Django 5.2.4 on 2025-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0011_emailcenter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcenter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='emailcenter',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='emailcenter',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('phone_number',), name='unique_phone_number'),
        ),
    ]
