# Generated by Django 5.2.4 on 2025-10-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0012_alter_emailcenter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailcenter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
