# Generated by Django 5.2.4 on 2025-10-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0013_alter_emailcenter_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailcenter',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='emailcenter',
            name='unique_phone_number',
        ),
    ]
