# Generated by Django 5.2.4 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0015_emailcenter_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcenter',
            name='can_access_web_app',
            field=models.BooleanField(default=False),
        ),
    ]
