# Generated by Django 5.2.4 on 2025-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='chat_group_pics/'),
        ),
    ]
