# Generated by Django 5.2.4 on 2025-09-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_pinnedchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted_for_users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted_for_everyone',
        ),
    ]
