# Generated by Django 5.2.4 on 2025-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_devicetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
