# Generated by Django 5.2.4 on 2025-08-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feedcomment_feedlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.feedcomment'),
        ),
    ]
