# Generated by Django 5.2.4 on 2025-08-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feedcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcomment',
            name='parent',
        ),
    ]
