# Generated by Django 5.2.4 on 2025-08-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_feedcomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
