# Generated by Django 5.2.4 on 2025-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_feedcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
